[versions]
java = "11"
kotlin = "1.9.23"

[libraries]
autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.1.1" }
autoservice-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "1.1.0" }

[plugins]
kotlin-ksp = { id = "com.google.devtools.ksp", version = "1.9.23-1.0.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-samReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
testkit-jacoco = { id = "pl.droidsonroids.jacoco.testkit", version = "1.0.12" }
