/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.gmazzo.gradle.publications.report

import org.gradle.kotlin.dsl.apply
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

class ReportPublicationsPluginTest {

    @Test
    fun `plugin registers service`() {
        val project = ProjectBuilder.builder().build()
        project.apply<ReportPublicationsPlugin>()

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }

}
